config/routes.rb
Rails.application.routes.draw do
  get "developer/index", as: "developer"
  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  post "home/fake", as: "fake"
  post "developer/runner", as: "runner"
  root "home#index"
end

app/controllers/developer_controller.rb
class DeveloperController < ApplicationController
  def index; end

  def runner
    url = params[:url]
    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
      "goog:chromeOptions": { args: ["headless", "disable-gpu", "user-agent=Analytics Robot"] },
    )
    driver = Selenium::WebDriver.for :chrome, capabilities: capabilities

    driver.get url
    accept_cookies(driver)
    click_elements(driver)

    events = driver.execute_script("if(window.dataLayer){ return window.dataLayer } else { return ['The dataLayer is unavailable on this page'] }")
    ActionCable.server.broadcast "developer_channel", events
    driver.quit
  end

private

  def accept_cookies(driver)
    element = driver.find_element(:css, "[data-accept-cookies]")
    element.click unless element.nil?
  rescue StandardError
    Rails.logger.debug "No GOV.UK cookies on page"
  end

  def click_elements(driver)

    header_search_button = driver.find_element(:css, "#super-search-menu-toggle")
    header_search_button.click unless header_search_button.nil?

    # We use JavaScript to fake the clicks, because Selenium errors when you try to interact with hidden elements.
    driver.execute_script('
      document.addEventListener("click", function(e) {
        e.preventDefault();
      })')
    driver.execute_script('
      document.addEventListener("submit", function(e) {
        e.preventDefault()
      })')

    driver.execute_script('window.ga4Links = document.querySelectorAll("[data-ga4-link]")')
    driver.execute_script('window.ga4Events = document.querySelectorAll("[data-ga4-event]")')
    driver.execute_script('window.ga4FormSubmits = document.querySelectorAll("[data-ga4-form] [type=submit]")')

    driver.execute_script(
      'for (var i = 0; i < window.ga4Links.length; i++) {
        window.GOVUK.triggerEvent(window.ga4Links[i], "click")
      }')

    driver.execute_script(
      'for (var i = 0; i < window.ga4Events.length; i++) {
        window.GOVUK.triggerEvent(window.ga4Events[i], "click")

        // If the element is expandable, like an accordion, click it twice so that it gives us both the open and closed state.
        if(window.ga4Events[i].closest("[data-ga4-expandable]")) {
          window.GOVUK.triggerEvent(window.ga4Events[i], "click")
        }
      }')

    driver.execute_script(
      'for (var i = 0; i < window.ga4FormSubmits.length; i++) {
        window.GOVUK.triggerEvent(window.ga4FormSubmits[i], "click")
      }')

  end
end

app/views/developer/index.html.erb
<div class="govuk-width-container ">
  <main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-full">
        <h1 class="govuk-heading-xl">See all GA4 events for a given page </h1>
        <p class="govuk-body">This page shows all the possible GA4 events for a given URL. This is a work in progress - only a few interactions are implemented.<p>
        <p class="govuk-body">Currently, this works by loading a page, and clicking every element with data-ga4-event, data-ga4-link, or data-ga4-form (with some JS to prevent default behaviour.)<p>
        <p class="govuk-body"><strong>Connect to the developer VPN to test on staging/integration environments.</strong></p>
        <%= form_with url: runner_path, method: :post do |form| %>
          <div class="govuk-form-group">
            <%= form.label :url, class: "govuk-label" %>
            <%= form.text_field :url, class: "govuk-input" %>
          </div>

          <%= form.submit "Process", class: "govuk-button" %>
        <% end %>

        <h2 class="govuk-heading-l">Output</h2>
        <%= turbo_frame_tag id="developer-output" do %>
        <% end %>
      </div>
    </div>
  </main>
</div>