config/routes.rb
Rails.application.routes.draw do
  get "developer/index", as: "developer"
  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  post "home/fake", as: "fake"
  post "developer/runner", as: "runner"
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @interaction_types = ApplicationController.helpers.interaction_types
    @environments = %w[integration.publishing.service.gov.uk staging.publishing.service.gov.uk gov.uk]
  end

  def fake
    params[:display] = "browser"
    FakerJob.perform_now params
  end
end

app/views/home/index.html.erb
<div class="govuk-width-container ">
  <main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-xl">Analytics Robot</h1>
        <h2 class="govuk-heading-m">Run our automated GA4 tests on an environment</h2>
        <p class="govuk-body">This form will run any tests listed in interactions.yaml on the chosen environment.</p>
        <p class="govuk-body"><strong>Connect to the developer VPN to test on staging/integration environments.</strong></p>

        <%= form_with url: fake_path, method: :post do |form| %>
          <div class="govuk-form-group">
            <%= form.label :environment, class: "govuk-label" %>
            <%= form.select :environment, @environments, { selected: @environments.first }, { class: "govuk-select" } %>
          </div>

          <div class="govuk-form-group">
            <%= form.label :interaction_type, class: "govuk-label" %>
            <%= form.select :interaction_type, @interaction_types, { selected: @interaction_types.first }, { class: "govuk-select" } %>
          </div>

          <div class="govuk-form-group">
            <%= form.label :iterations, class: "govuk-label" %>
            <%= form.number_field :iterations, value: 1, class: "govuk-input govuk-input--width-10" %>
          </div>

          <%= form.submit "Process", class: "govuk-button" %>
        <% end %>

        <h2 class="govuk-heading-l">Output</h2>
        <%= turbo_frame_tag id="faker-output" do %>
        <% end %>
      </div>
      <div class="govuk-grid-column-one-third">
        <ul class="govuk-list">
          <li>
            <%= link_to "Get 10 random pageview objects on Integration", fake_path(environment: "integration.publishing.service.gov.uk", interaction_type: "random", iterations: 10), data: { turbo_method: "post" }, class: "govuk-link" %>
          </li>
          <li>
            <hr>
          </li>
          <li>
            <%= link_to "See all GA4 events for a given page", developer_path, class: "govuk-link" %>
          </li>
        </ul>
      </div>
    </div>
  </main>
</div>